""""""""""""""""""""""""""""""""""""""
" The vimrc file of Dakota Nelson    "
" Adapted from that of Evan Morikawa "
""""""""""""""""""""""""""""""""""""""

"""""""""""""""""""
" Vundle Packages "
"""""""""""""""""""

" Simply type :BundleInstall to install everything.

set nocompatible " Does not use old vi quirks
filetype off     " Required temporarily for vundle
set rtp+=~/.vim/bundle/Vundle.vim
call vundle#rc()

" Helps me collaborate "
""""""""""""""""""""""""
" A Git wrapper so awesome, it should be illegal
Bundle 'tpope/vim-fugitive'

" Helps me see "
""""""""""""""""
" Colors CSS tags with the appropriate color.
Bundle 'skammer/vim-css-color'

" Add CSS3 syntax support to vim's built-in `syntax/css.vim`
Bundle 'hail2u/vim-css3-syntax'

" Markdown syntax for vim
Bundle 'tpope/vim-markdown'

" Shows indent level
Bundle 'nathanaelkane/vim-indent-guides'

" Solarized color schemes. We use Dakota's color scheme for dark and
" Solarized for light bg.
Bundle 'altercation/vim-colors-solarized'

" Helps me search "
"""""""""""""""""""
Bundle 'grep.vim'

" Helps me move "
"""""""""""""""""
" A tree explorer plugin for vim
" <c-n>
Bundle 'scrooloose/nerdtree'

" Unload/delete/wipe a buffer, keep its window(s)
" Bundle 'bufkill.vim'

" Helps me code "
"""""""""""""""""
Bundle 'vim-syntastic/syntastic'
let g:syntastic_python_checkers = ['pylint']

let g:syntastic_always_populate_loc_list = 1
let g:syntastic_auto_loc_list = 1
let g:syntastic_check_on_open = 0
let g:syntastic_check_on_wq = 0

" Helps me develop in Go
Bundle 'fatih/vim-go'
" Disable Shift-k looking up Godocs (so that I can use it for fast movement)
let g:go_doc_keywordprg_enabled = 0

" Helps me type "
"""""""""""""""""
" Quoting/parenthesizing made simple
" cs<match><replace> - change surroundings
" ds<match> - delete surroundings
" v<selection>S<replacement> - wrap visual selection with surrounding of choice
" ysiw<surrounding> - wrap word with surrounding of choice
" yss<surrounding> - wrap line with surrounding of choice
Bundle 'tpope/vim-surround'

" Enable repeating supported plugin maps with '.'
Bundle 'tpope/vim-repeat'

" Enable case coercion, among other things
" :S/facilit{y,ies}/building{,s}/g
Bundle 'tpope/vim-abolish'

" Easily comment in and out lines
" gcc - toggle comment for current line
Bundle 'tomtom/tcomment_vim'

" Vim motions on speed. Replaces the <number> in <number><motion>
" <leader><leader><motion>
Bundle 'Lokaltog/vim-easymotion'

" Key remappings ordered by approximate frequency of use"
"""""""""""""""""""""""""""""""""""""""""""""""""""""""""
let mapleader = ","

"Quick escape and saving via button-mashing
inoremap jk <Esc>
inoremap kj <Esc>
cnoremap jk <Esc>
cnoremap kj <Esc>
inoremap df <Esc>:w<CR>
inoremap fd <Esc>:w<CR>
noremap df :w<CR>
noremap fd :w<CR>

"Easier movement around the page
noremap <C-j> 3<C-e>
noremap <C-k> 3<C-y>
noremap <S-j> 3j
noremap <S-k> 3k
noremap <S-l> 5l
noremap <S-h> 5h
noremap <PageUp> <c-u>
noremap <PageDown> <c-d>
noremap <Home> 0
noremap <End> $
noremap j gj
noremap k gk
noremap 0 ^

"Move between buffers
noremap <c-h> <c-w>h
noremap <c-l> <c-w>l

" Unhighlight
"noremap <S-Space> :nohl<CR>
" Space bar searching
noremap <Space> /

noremap <F1> <nop>

" Syntax checking commands
noremap sc :SyntasticCheck<CR>
noremap scc :SyntasticReset<CR>
noremap ne :lnext<CR>
noremap pe :lprevious<CR>

"Git commands
noremap gs :Gstatus<CR>
noremap ga :Gwrite<CR>
noremap gc :Gcommit -a<CR>
noremap gd :Gdiff<CR>
noremap gl :Gdiff HEAD~1<CR>
noremap gb :Gbrowse<CR>

"Reselect visual block after indent/outdent
vnoremap < <gv
vnoremap > >gv

" Edit Vimrc
" $MYVIMRC points to the ~/.vimrc file
nnoremap <leader>ev :e $MYVIMRC<CR>
" Re-source vimrc
nnoremap <leader>sv :source $MYVIMRC<CR>

" noremap <C-Q> <esc>:bd<CR>:vsp<CR>:bn<CR>:buffers<CR>
noremap <C-Q> <esc>:bd<CR>

"Info about the character underneath cursor
nnoremap gi ga

" Toggles paste mode and shows value of the option
nnoremap <F2> :set invpaste paste?<CR>
noremap <C-S> :%s/

"Smart folding on shift-space
nnoremap <silent> zz @=(foldlevel('.')?'za':'l')<CR>
vnoremap zz zf

"shell shortcuts in command mode
cnoremap <C-A> <Home>
cnoremap <C-E> <End>
cnoremap <C-K> <C-U>
cnoremap <C-P> <Up>
cnoremap <C-N> <Down>

"Displays the tag type under the cursor. Really useful for generating colors
map <c-x> :echo "hi<" . synIDattr(synID(line("."),col("."),1),"name") . '> trans <'
\ . synIDattr(synID(line("."),col("."),0),"name") . "> lo<"
\ . synIDattr(synIDtrans(synID(line("."),col("."),1)),"name") . ">"<CR>

" Remove the Windows ^M - when the encodings gets messed up
noremap <Leader>m mmHmt:%s/<C-V><cr>//ge<cr>'tzt'm

" Settings "
""""""""""""
filetype plugin indent on " Turn on filetype after Vundle is setup
colorscheme dakota
syntax enable

set nu "Turn on line numbers
set list "All characters print. Including meta characters
set ts=2
set sw=2
set ruler "Shows the ruler
set magic "set magic on, for regular expressions
set mat=2 "two-tenths of a second blink
set smarttab
set wildmenu "Enhanced tab completion
set autoread "Set to auto read when a file is changed from the outside
set vb t_vb= "disables visual bell
set hlsearch
set showmode "Says whether or not paste mode is turned on or off
set t_Co=256 "Enable colored terminal
let &t_Co=256
set incsearch "Incremental search
set smartcase "Will switch to case sensitive if a cap is used
set showmatch "Shows matches on search
set expandtab "Replaces tabs with spaces
set tabstop=2 "Num characters when tab is pushed
set ignorecase "case insensitive search (except smartcase)
set autoindent "Enable automatic alignment during insertions
set noswapfile "Don't use swp files
set cindent "Tries to recognize code and indent
set textwidth=0 "Don't hard wrap lines
set cmdheight=2 "The commandbar height
set noerrorbells
set novisualbell
set history=1000
set laststatus=2 "Always show the status line
set restorescreen
set encoding=utf8
set shell=/bin/sh "Use bash shell
set guioptions-=T "Removes GUI bars
set guioptions-=l "Removes scrollbars
set guioptions-=r "Removes scrollbars
set guioptions-=b "Removes scrollbars
set colorcolumn=80
set pastetoggle=<F2> " Binds F2 to pastetoggling
let c_minlines = 300 " scan 300 lines to find proper syntax highlighting
set wildmode=list:longest,full " bash command line tab completion
set listchars=tab:\|\ ,trail:●,extends:>,precedes:<,nbsp:+ "Whitespace showing
set statusline=%<%f\ %h%m%r%{fugitive#statusline()}%=%-14.(%l,%c%V%)\ %P

" Custom commands "
"""""""""""""""""""
" Removes all trailing whitespace
command! Whitespace %s/\s\+$//e

command! -nargs=1 Gr Grep -ErinI --exclude-dir=log --exclude-dir=tmp --exclude-dir=coverage <args> *

" Open the file being edited in gedit
command! Editor ! gedit "%"

" Profiling
command StartProfile :profile start profile.log | profile func * | profile file *
command StopProfile :profile pause

" Autocommands "
"""""""""""""""

" Makes sure Vim resets colors on exit "
au VimLeave * !echo -ne "\033[0m"

" Utility Methods "
""""""""""""""""""
"match LineTooLong /\%>74v.\+/

function! DeleteTrailingWS()
  exe "normal mz"
  %s/\s\+$//ge
  exe "normal `z"
endfunc

""""""""""""""""""""""""""""""
" Language Specific Settings "
""""""""""""""""""""""""""""""

" Python "
""""""""""
augroup python_helpers
  autocmd!
  au FileType python setl
      \ tabstop=4
      \ softtabstop=4
      \ shiftwidth=4

  au BufWrite *.py :call DeleteTrailingWS() "Deletes trailing whitepace
  let python_highlight_all = 1
  au FileType python syn keyword pythonDecorator True None False self

  au BufNewFile,BufRead *.jinja set syntax=htmljinja
  au BufNewFile,BufRead *.mako set ft=mako
  au BufNewFile,BufRead *.less set ft=less
augroup END

let &t_Sf="\<Esc>[3%dm"
let &t_Sb="\<Esc>[4%dm"
let &t_te="\<Esc>[?47l"
let &t_ti="\<Esc>[?47h"

"""""""""""
" PLUGINS "
"""""""""""
" Nerd Tree "
"""""""""""""
noremap <c-n> :NERDTreeToggle<CR>

" Vim Indent Guides "
"""""""""""""""""""""
let g:indent_guides_auto_colors = 0
augroup indent_guides
  autocmd!
  au BufRead,BufNewFile * IndentGuidesEnable
augroup END
